name: IgelBingo
version: 1.0.8
main: de.igelbingo.IgelBingoGamePlugin
api-version: "26.1.2"
description: Game management plugin for Igel-Bingo (replaces bingo_purpur datapack)
authors: [Igelway]
depend: [BingoReloaded]

commands:
  igelbingo:
    description: IgelBingo game management commands
    usage: /igelbingo <start|end|firststart|abort>
    permission: igelbingo.admin

permissions:
  igelbingo.admin:
    description: Access to IgelBingo admin commands
    default: op
